import { getLensLabel, normalizeProfileId } from "@/lib/lenses";
import { createLayerState } from "@/lib/map-layers";
import { MissionProfile } from "@/types";

export const PROFILES: MissionProfile[] = [
  {
    id: "data-center",
    name: getLensLabel("data-center"),
    icon: "Server",
    tagline: "Water, power, and thermal efficiency",
    description:
      "Evaluate sites for data center cooling with an emphasis on water access, power infrastructure, terrain, and climate.",
    accentColor: "#00e5ff",
    factors: [
      {
        key: "waterProximity",
        label: "Cooling water access",
        weight: 0.26,
        scoreFn: "custom",
        params: { metric: "waterAccess" },
        description: "Combines mapped water proximity with nearby USGS stream gauge distance and discharge volume.",
      },
      {
        key: "terrain",
        label: "Elevation & flatness",
        weight: 0.12,
        scoreFn: "elevation",
        params: { mode: "cooling" },
        description: "Flatter, lower-elevation sites are easier to develop and cool.",
      },
      {
        key: "powerInfrastructure",
        label: "Power infrastructure",
        weight: 0.18,
        scoreFn: "distance",
        params: { source: "power", idealKm: 2, cutoffKm: 20, direction: "near" },
        description: "Close proximity to substations or transmission corridors reduces utility friction.",
      },
      {
        key: "climate",
        label: "Climate suitability",
        weight: 0.13,
        scoreFn: "climate",
        params: { mode: "cooling" },
        description: "Cooler average temperatures and lower cooling demand improve suitability.",
      },
      {
        key: "transportation",
        label: "Road transportation",
        weight: 0.07,
        scoreFn: "distance",
        params: { source: "road", idealKm: 2, cutoffKm: 18, direction: "near" },
        description: "Closer road access helps with construction and operations logistics.",
      },
      {
        key: "landClassification",
        label: "Land classification",
        weight: 0.06,
        scoreFn: "landcover",
        params: { mode: "developed" },
        description: "Previously developed, industrial, or barren land is favored.",
      },
      {
        key: "broadbandConnectivity",
        label: "Broadband readiness",
        weight: 0.1,
        scoreFn: "custom",
        params: { metric: "broadbandConnectivity", mode: "data_center" },
        description: "Uses FCC provider count and peak download/upload capacity as an early connectivity signal.",
      },
      {
        key: "floodRisk",
        label: "Flood risk",
        weight: 0.01,
        scoreFn: "custom",
        params: { metric: "floodRisk" },
        description: "Uses FEMA flood-zone designation to lightly penalize infrastructure risk in mapped SFHAs.",
      },
      {
        key: "contaminationRisk",
        label: "Contamination risk",
        weight: 0.01,
        scoreFn: "custom",
        params: { metric: "contaminationRisk" },
        description: "Uses EPA Superfund and TRI screening to lightly penalize nearby contamination context.",
      },
      {
        key: "groundwaterDepth",
        label: "Groundwater depth",
        weight: 0.02,
        scoreFn: "custom",
        params: { metric: "groundwaterDepth", mode: "data_center" },
        description: "Deeper water tables reduce dewatering and foundation complexity for infrastructure build-out.",
      },
      {
        key: "soilBuildability",
        label: "Soil buildability",
        weight: 0.02,
        scoreFn: "custom",
        params: { metric: "soilBuildability" },
        description: "Well-drained soils and stronger hydrologic groups support easier grading and foundation work.",
      },
      {
        key: "seismicRisk",
        label: "Seismic risk",
        weight: 0.01,
        scoreFn: "custom",
        params: { metric: "seismicRisk" },
        description: "Lower peak ground acceleration reduces structural reinforcement burden for major facilities.",
      },
      {
        key: "hazardAlerts",
        label: "Regional disaster alerts",
        weight: 0.01,
        scoreFn: "custom",
        params: { metric: "hazardAlerts" },
        description: "Uses GDACS live global disaster feed to lightly penalize sites in currently elevated-alert regions.",
      },
    ],
    systemPrompt:
      "You are a geospatial intelligence expert focused on data center cooling and digital infrastructure siting. Prioritize water access, power grid adjacency, terrain buildability, climate suitability, and environmental constraints. Be explicit about what is supported by geodata versus what still needs permitting, engineering, or utility diligence.",
    defaultLayers: createLayerState({
      roads: true,
      floodZones: true,
    }),
    exampleQuestions: [
      "Can this site support evaporative cooling?",
      "How far is the nearest substation or transmission corridor?",
      "What cooling risks stand out here?",
      "Would this work for a hyperscale campus?",
    ],
    recommendationBands: [
      { min: 85, text: "Excellent data-center cooling candidate with strong infrastructure alignment." },
      { min: 70, text: "Promising cooling site with a few constraints to validate in due diligence." },
      { min: 55, text: "Potentially viable only if permitting, grading, or utility issues are solved." },
      { min: 0, text: "Weak cooling-site fit compared with stronger regional benchmarks." },
    ],
  },
  {
    id: "hiking",
    name: getLensLabel("hiking"),
    icon: "Trees",
    tagline: "Trails, views, water, and remoteness",
    description:
      "Use this lens to evaluate day-hike or outdoor recreation potential based on terrain variety, vegetation, water features, access, and climate comfort.",
    accentColor: "#5be49b",
    factors: [
      {
        key: "terrainVariety",
        label: "Terrain variety",
        weight: 0.23,
        scoreFn: "custom",
        params: { metric: "terrainVariety" },
        description: "Moderate elevation gain and terrain variety improve hiking appeal.",
      },
      {
        key: "vegetationDensity",
        label: "Vegetation density",
        weight: 0.18,
        scoreFn: "landcover",
        params: { mode: "vegetation" },
        description: "Forested and vegetated landscapes generally increase recreation value.",
      },
      {
        key: "waterFeatures",
        label: "Water features nearby",
        weight: 0.19,
        scoreFn: "distance",
        params: { source: "water", idealKm: 0.5, cutoffKm: 12, direction: "near" },
        description: "Waterfalls, rivers, lakes, and streams increase trail destination value.",
      },
      {
        key: "remoteness",
        label: "Distance from urban areas",
        weight: 0.15,
        scoreFn: "custom",
        params: { metric: "remoteness" },
        description: "A modest buffer from major roads can improve the feeling of remoteness.",
      },
      {
        key: "trailAccess",
        label: "Trail access",
        weight: 0.08,
        scoreFn: "custom",
        params: { metric: "trailAccess" },
        description: "Blends OSM-mapped trailhead and hiking-path counts with road proximity for day-use logistics.",
      },
      {
        key: "weather",
        label: "Climate / weather",
        weight: 0.09,
        scoreFn: "climate",
        params: { mode: "outdoor" },
        description: "Moderate temperatures and manageable precipitation support broader usability.",
      },
      {
        key: "airQuality",
        label: "Air quality",
        weight: 0.08,
        scoreFn: "custom",
        params: { metric: "airQuality" },
        description: "Uses OpenAQ PM2.5 and PM10 station readings, with Open-Meteo AQI as a fallback context signal.",
      },
    ],
    systemPrompt:
      "You are a geospatial intelligence expert focused on hiking, trail planning, and outdoor recreation suitability. Emphasize terrain character, water features, vegetation, access, remoteness, and weather comfort. When uncertainty exists, make it clear whether you are using direct geodata, live mapped nearby places, or inference about scenic and recreation value.",
    defaultLayers: createLayerState({
      roads: true,
      fires: true,
      contours: true,
    }),
    exampleQuestions: [
      "What's the terrain difficulty here?",
      "Are there water features for a day hike?",
      "How remote does this area feel?",
      "Would this support a scenic trail network?",
    ],
    recommendationBands: [
      { min: 85, text: "Outstanding outdoor recreation candidate with strong terrain and scenic signals." },
      { min: 70, text: "Promising hiking area with a few access or climate tradeoffs." },
      { min: 55, text: "Usable for recreation, but not a standout trail destination without more validation." },
      { min: 0, text: "Limited recreation appeal compared with stronger hiking candidates." },
    ],
  },
  {
    id: "home-buying",
    name: getLensLabel("home-buying"),
    icon: "House",
    tagline: "Neighborhood fit, schools, and daily-life access",
    description:
      "Screen neighborhoods with a consumer-first lens that emphasizes schools, amenities, connectivity, environmental quality, and day-to-day livability.",
    accentColor: "#ffab00",
    factors: [
      {
        key: "schoolAccess",
        label: "School access",
        weight: 0.2,
        scoreFn: "custom",
        params: { metric: "schoolAccess" },
        description: "Uses nearby public-school context and official Washington accountability where available.",
      },
      {
        key: "amenities",
        label: "Daily amenities",
        weight: 0.18,
        scoreFn: "custom",
        params: { metric: "amenities" },
        description: "Uses live mapped grocery, restaurant, and service density as an everyday convenience signal.",
      },
      {
        key: "roadTransit",
        label: "Commute and access",
        weight: 0.15,
        scoreFn: "distance",
        params: { source: "road", idealKm: 1.5, cutoffKm: 14, direction: "near" },
        description: "Closer road access supports commuting and daily mobility.",
      },
      {
        key: "broadbandConnectivity",
        label: "Internet quality",
        weight: 0.12,
        scoreFn: "custom",
        params: { metric: "broadbandConnectivity", mode: "residential" },
        description: "Uses FCC provider count and speeds as a work-from-home and streaming readiness signal.",
      },
      {
        key: "floodRisk",
        label: "Flood risk",
        weight: 0.12,
        scoreFn: "custom",
        params: { metric: "floodRisk" },
        description: "Uses FEMA flood-zone designation as an early caution signal where supported.",
      },
      {
        key: "airQuality",
        label: "Air quality",
        weight: 0.1,
        scoreFn: "custom",
        params: { metric: "airQuality" },
        description: "Uses station readings and AQI fallback to screen for everyday environmental quality.",
      },
      {
        key: "buildability",
        label: "Terrain practicality",
        weight: 0.06,
        scoreFn: "elevation",
        params: { mode: "buildability" },
        description: "Moderate terrain is easier for day-to-day access and future maintenance.",
      },
      {
        key: "landClassification",
        label: "Neighborhood land mix",
        weight: 0.04,
        scoreFn: "landcover",
        params: { mode: "residential" },
        description: "Favors mixed residential and urban land cover over heavily constrained surfaces.",
      },
      {
        key: "contaminationRisk",
        label: "Environmental caution",
        weight: 0.03,
        scoreFn: "custom",
        params: { metric: "contaminationRisk" },
        description: "Uses EPA screening to flag unusually close contamination context where supported.",
      },
    ],
    systemPrompt:
      "You are a geospatial intelligence assistant focused on home buying and neighborhood screening. Prioritize school access, daily amenities, commute practicality, internet quality, flood exposure, air quality, and plain-language livability signals. Speak clearly for ordinary buyers, keep technical jargon behind short explanations, and state openly when a signal is unsupported or only approximate.",
    defaultLayers: createLayerState({
      roads: true,
      floodZones: true,
    }),
    exampleQuestions: [
      "Does this feel like a strong place to buy a home?",
      "How good is the school and amenity access here?",
      "What daily-life risks or tradeoffs stand out?",
      "Would this work well for a family moving here?",
    ],
    recommendationBands: [
      { min: 85, text: "Strong home-buying signal with good access, livability, and few obvious early risks." },
      { min: 70, text: "Promising neighborhood with a few tradeoffs worth checking more closely." },
      { min: 55, text: "Potentially workable for home buying, but some quality-of-life or risk questions remain." },
      { min: 0, text: "Weak home-buying fit compared with stronger nearby neighborhoods." },
    ],
  },
  {
    id: "site-development",
    name: getLensLabel("site-development"),
    icon: "Building2",
    tagline: "Buildability, hazards, and development readiness",
    description:
      "Evaluate land for neighborhood-scale residential growth using access, buildability, hazard proxies, amenity signals, and general development readiness.",
    accentColor: "#ffab00",
    factors: [
      {
        key: "schoolAccess",
        label: "School district proximity",
        weight: 0.15,
        scoreFn: "custom",
        params: { metric: "schoolAccess" },
        description: "Uses nearby public-school context from NCES and Washington official accountability when available.",
      },
      {
        key: "roadTransit",
        label: "Road / transit access",
        weight: 0.13,
        scoreFn: "distance",
        params: { source: "road", idealKm: 1.5, cutoffKm: 14, direction: "near" },
        description: "Closer access supports commuting and neighborhood connectivity.",
      },
      {
        key: "buildability",
        label: "Terrain buildability",
        weight: 0.12,
        scoreFn: "elevation",
        params: { mode: "buildability" },
        description: "Moderate, more buildable terrain scores higher.",
      },
      {
        key: "floodRisk",
        label: "Flood risk",
        weight: 0.13,
        scoreFn: "custom",
        params: { metric: "floodRisk" },
        description: "Uses FEMA flood-zone designation so Zone X carries no penalty while mapped SFHAs create an approximate fifteen-point total-score penalty.",
      },
      {
        key: "amenities",
        label: "Commercial amenities nearby",
        weight: 0.09,
        scoreFn: "custom",
        params: { metric: "amenities" },
        description: "Uses live mapped amenity density from OpenStreetMap.",
      },
      {
        key: "landClassification",
        label: "Land classification",
        weight: 0.09,
        scoreFn: "landcover",
        params: { mode: "residential" },
        description: "Avoids water-heavy land and favors mixed open or already-developed parcels.",
      },
      {
        key: "broadbandConnectivity",
        label: "Broadband readiness",
        weight: 0.07,
        scoreFn: "custom",
        params: { metric: "broadbandConnectivity", mode: "residential" },
        description: "Uses FCC provider count and peak speeds as a residential connectivity factor.",
      },
      {
        key: "airQuality",
        label: "Air quality",
        weight: 0.08,
        scoreFn: "custom",
        params: { metric: "airQuality" },
        description: "Uses OpenAQ particle readings, with Open-Meteo AQI fallback, as an environmental quality signal.",
      },
      {
        key: "contaminationRisk",
        label: "Contamination risk",
        weight: 0.06,
        scoreFn: "custom",
        params: { metric: "contaminationRisk" },
        description: "Uses EPA Superfund and TRI proximity as an early contamination-screening factor.",
      },
      {
        key: "groundwaterDepth",
        label: "Groundwater depth",
        weight: 0.03,
        scoreFn: "custom",
        params: { metric: "groundwaterDepth", mode: "residential" },
        description: "Moderate water-table depth is generally easier for housing foundations and yard drainage.",
      },
      {
        key: "soilBuildability",
        label: "Soil buildability",
        weight: 0.03,
        scoreFn: "custom",
        params: { metric: "soilBuildability" },
        description: "Well-drained soils with stronger hydrologic groups improve neighborhood buildability and drainage resilience.",
      },
      {
        key: "seismicRisk",
        label: "Seismic risk",
        weight: 0.01,
        scoreFn: "custom",
        params: { metric: "seismicRisk" },
        description: "Lower site shaking potential improves early residential risk screening.",
      },
      {
        key: "hazardAlerts",
        label: "Regional disaster alerts",
        weight: 0.01,
        scoreFn: "custom",
        params: { metric: "hazardAlerts" },
        description: "Uses GDACS live global disaster feed to lightly penalize sites in currently elevated-alert regions.",
      },
    ],
    systemPrompt:
      "You are a geospatial intelligence expert focused on residential site development and neighborhood planning. Emphasize buildability, access, hazards, school context, amenity context, and community readiness. Distinguish official government school accountability data from GeoSight's derived school-context score, and state clearly when school coverage is unsupported outside the current US-first pipeline.",
    defaultLayers: createLayerState({
      roads: true,
      floodZones: true,
    }),
    exampleQuestions: [
      "Is this land suitable for a new neighborhood?",
      "What risks or constraints would slow housing here?",
      "How accessible is this to nearby services?",
      "Does this feel more suburban or rural?",
    ],
    recommendationBands: [
      { min: 85, text: "Strong residential site-development candidate with good access and few obvious buildability issues." },
      { min: 70, text: "Promising housing site with some hazard or amenity tradeoffs to review." },
      { min: 55, text: "Possible residential site, but key infrastructure or risk constraints remain unresolved." },
      { min: 0, text: "Weak neighborhood-development fit without major infrastructure or entitlement changes." },
    ],
  },
  {
    id: "commercial",
    name: getLensLabel("commercial"),
    icon: "Warehouse",
    tagline: "Access, demand, and utility readiness",
    description:
      "Use this profile for retail, commercial, and warehouse siting questions tied to highway access, inferred commercial activity, utility proximity, and development practicality.",
    accentColor: "#a78bfa",
    factors: [
      {
        key: "trafficPopulation",
        label: "Traffic / population density",
        weight: 0.25,
        scoreFn: "custom",
        params: { metric: "commercialDemand" },
        description: "Uses road access and urbanized land-cover as an early demand proxy.",
      },
      {
        key: "freightAccess",
        label: "Highway / freight access",
        weight: 0.2,
        scoreFn: "distance",
        params: { source: "road", idealKm: 1.2, cutoffKm: 12, direction: "near" },
        description: "Closer highway corridors improve logistics and commercial throughput.",
      },
      {
        key: "commercialDensity",
        label: "Existing commercial density",
        weight: 0.15,
        scoreFn: "custom",
        params: { metric: "commercialDensity" },
        description: "Uses developed land-cover, roads, and utilities as a proxy for existing activity.",
      },
      {
        key: "landCostIndicators",
        label: "Land cost indicators",
        weight: 0.15,
        scoreFn: "custom",
        params: { metric: "landCost" },
        description: "Uses distance from core infrastructure and land-cover mix as an early cost heuristic.",
      },
      {
        key: "utilities",
        label: "Utility infrastructure",
        weight: 0.15,
        scoreFn: "distance",
        params: { source: "power", idealKm: 2, cutoffKm: 18, direction: "near" },
        description: "Commercial and warehouse operations benefit from nearby utility corridors.",
      },
      {
        key: "terrain",
        label: "Terrain flatness",
        weight: 0.1,
        scoreFn: "elevation",
        params: { mode: "buildability" },
        description: "Flatter sites reduce grading complexity for commercial build-out.",
      },
    ],
    systemPrompt:
      "You are a geospatial intelligence expert focused on retail, commercial real estate, and warehouse siting. Prioritize freight and road access, inferred demand, utility readiness, and land practicality. Be explicit when demand, traffic, or land-cost commentary is based on proxy signals rather than live demographic or parcel data. When analyzing locations outside the US, note that demographic data comes from World Bank national indicators rather than county-level census data, and school context is not yet available.",
    defaultLayers: createLayerState({
      roads: true,
      floodZones: true,
    }),
    exampleQuestions: [
      "How strong is the highway access here?",
      "Would this work for a distribution warehouse?",
      "Does this area look commercially active already?",
      "What operational constraints stand out for retail or logistics?",
    ],
    recommendationBands: [
      { min: 85, text: "Excellent commercial or logistics candidate with strong access and utility support." },
      { min: 70, text: "Promising commercial site with manageable market or site-readiness tradeoffs." },
      { min: 55, text: "Potential fit for commercial use, but important demand or build-out questions remain." },
      { min: 0, text: "Weak commercial / warehouse fit relative to stronger corridor candidates." },
    ],
  },
];

export const DEFAULT_PROFILE = PROFILES[0];

export const PROFILE_MAP = Object.fromEntries(PROFILES.map((profile) => [profile.id, profile])) as Record<
  string,
  MissionProfile
>;

export function getProfileById(profileId: string | null | undefined) {
  const normalizedProfileId = normalizeProfileId(profileId);
  return (normalizedProfileId ? PROFILE_MAP[normalizedProfileId] : undefined) ?? DEFAULT_PROFILE;
}
