import {
  WorkspaceCardDefinition,
  WorkspaceCardId,
  WorkspaceCardPreference,
} from "@/types";

export const WORKSPACE_CARD_REGISTRY: WorkspaceCardDefinition[] = [
  {
    id: "active-location",
    title: "Active location",
    summary: "Pin the current place and scan the key trust signals.",
    questionAnswered: "What is the current place and how trustworthy is the data around it?",
    regionCoverage: "Global - coverage quality varies by source domain",
    failureMode: "Shows available fields with status badges; null values shown as '--'",
    freshnessWindow: "Live on location change",
    nextActions: ["Open source awareness for full provenance", "Ask GeoSight a question", "Save site to comparison"],
    icon: "MapPin",
    category: "context",
    zone: "primary",
    emphasis: "primary",
    defaultSize: "wide",
    defaultVisibility: true,
    defaultOrder: 10,
    requiredData: [],
    supportedProfiles: ["data-center", "hiking", "residential", "commercial"],
    emptyState: "Select a place to see the current map focus and quick context.",
  },
  {
    id: "chat",
    title: "Ask GeoSight",
    summary: "Ask mission-aware questions grounded in the active place.",
    questionAnswered: "How should GeoSight interpret this place through the active mission lens?",
    regionCoverage: "Global - bounded by active geodata coverage",
    failureMode: "Falls back from Groq to Gemini to deterministic assessment",
    freshnessWindow: "Live per question",
    nextActions: ["Ask a follow-up question", "Switch between analysis and nearby places mode", "Open sources to inspect coverage"],
    icon: "MessageSquare",
    category: "analysis",
    zone: "primary",
    emphasis: "primary",
    defaultSize: "wide",
    defaultVisibility: true,
    defaultOrder: 20,
    requiredData: [],
    supportedProfiles: ["data-center", "hiking", "residential", "commercial"],
    emptyState: "Choose a place to start asking questions.",
  },
  {
    id: "results",
    title: "Results",
    summary: "Switch between trend summaries and nearby place discovery.",
    questionAnswered: "What are the strongest signals and nearby destinations around this place?",
    regionCoverage: "Global - nearby places depend on OpenStreetMap completeness",
    failureMode: "Shows loading state, empty results, or unavailable source messaging",
    freshnessWindow: "Analysis trends refresh on geodata change; nearby places on category/location change",
    nextActions: ["Open a trend or place for follow-up reasoning", "Switch categories", "Save a site for comparison"],
    icon: "PanelsTopLeft",
    category: "analysis",
    zone: "primary",
    emphasis: "primary",
    defaultSize: "wide",
    defaultVisibility: true,
    defaultOrder: 30,
    requiredData: [],
    supportedProfiles: ["data-center", "hiking", "residential", "commercial"],
    emptyState: "Switch between map analysis and nearby places for the active location.",
  },
  {
    id: "mission-run",
    title: "Mission run",
    summary: "Run a judge-facing multi-step briefing for the active competition story.",
    questionAnswered: "What is GeoSight's structured verdict for this prepared demo story?",
    regionCoverage: "Competition presets only; currently Columbia River, Tokyo, and Washington residential",
    failureMode: "Falls back to deterministic mission summaries if model providers fail",
    freshnessWindow: "Live on each mission run",
    nextActions: ["Open the recommended supporting cards", "Rerun after changing location", "Use judge mode for presentation flow"],
    icon: "Sparkles",
    category: "analysis",
    zone: "workspace",
    emphasis: "primary",
    defaultSize: "wide",
    defaultVisibility: false,
    defaultOrder: 35,
    requiredData: ["mission-run"],
    supportedProfiles: ["data-center", "commercial", "residential"],
    emptyState: "Open this to run a structured competition briefing for the active story.",
  },
  {
    id: "score",
    title: "Mission score",
    summary: "See the weighted suitability score for this mission.",
    questionAnswered: "How suitable is this location for the current mission profile?",
    regionCoverage: "Global - strongest where supporting live sources are available",
    failureMode: "Hides until geodata is ready; score factors degrade individually when data is missing",
    freshnessWindow: "Recomputed on geodata change",
    nextActions: ["Open factor breakdown", "Compare saved sites", "Use score as a first-pass shortlist signal"],
    icon: "Gauge",
    category: "planning",
    zone: "workspace",
    emphasis: "secondary",
    defaultSize: "wide",
    defaultVisibility: true,
    defaultOrder: 40,
    requiredData: ["score"],
    supportedProfiles: ["data-center", "hiking", "residential", "commercial"],
    emptyState: "GeoSight will calculate a mission score when geodata is ready.",
  },
  {
    id: "factor-breakdown",
    title: "Factor breakdown",
    summary: "Inspect how each factor changed the score.",
    questionAnswered: "Why did the mission score move up or down?",
    regionCoverage: "Global - depends on underlying score inputs",
    failureMode: "Shows only the factors that can be scored from the current geodata",
    freshnessWindow: "Recomputed on geodata change",
    nextActions: ["Inspect evidence types", "Open source awareness", "Compare factor behavior across sites"],
    icon: "BarChart3",
    category: "planning",
    zone: "workspace",
    emphasis: "secondary",
    defaultSize: "standard",
    defaultVisibility: false,
    defaultOrder: 50,
    requiredData: ["score"],
    supportedProfiles: ["data-center", "hiking", "residential", "commercial"],
    emptyState: "Open this to see the score explained factor by factor.",
  },
  {
    id: "compare",
    title: "Comparison",
    summary: "Review saved locations side by side.",
    questionAnswered: "Which saved candidate looks strongest once the same factors are compared side by side?",
    regionCoverage: "Global - driven by whatever saved sites the user captured",
    failureMode: "Prompts for more saved sites until at least two are available",
    freshnessWindow: "Updates when saved sites change",
    nextActions: ["Save another site", "Open source awareness for a compared site", "Use comparison to tell the demo story"],
    icon: "Columns3",
    category: "comparison",
    zone: "workspace",
    emphasis: "optional",
    defaultSize: "wide",
    defaultVisibility: false,
    defaultOrder: 60,
    requiredData: ["saved-sites"],
    supportedProfiles: ["data-center", "hiking", "residential", "commercial"],
    emptyState: "Save at least two sites to unlock side-by-side comparison.",
  },
  {
    id: "terrain-viewer",
    title: "Terrain tools",
    summary: "Adjust terrain exaggeration and framing.",
    questionAnswered: "How does the landscape feel when I exaggerate or reframe the terrain?",
    regionCoverage: "Global where Cesium terrain is available",
    failureMode: "Terrain controls remain interactive even if analysis data is missing",
    freshnessWindow: "Immediate client-side interaction",
    nextActions: ["Adjust exaggeration", "Open elevation profile", "Zoom to another sub-area"],
    icon: "Mountain",
    category: "terrain",
    zone: "workspace",
    emphasis: "secondary",
    defaultSize: "standard",
    defaultVisibility: false,
    defaultOrder: 70,
    requiredData: [],
    supportedProfiles: ["data-center", "hiking", "residential", "commercial"],
    emptyState: "Open terrain tools for exaggeration and fly-around controls.",
  },
  {
    id: "elevation-profile",
    title: "Elevation profile",
    summary: "Inspect a sampled terrain transect through the region.",
    questionAnswered: "How does elevation change across the active region?",
    regionCoverage: "US high-res via USGS; global fallback via OpenTopoData",
    failureMode: "Returns partial or null transect values when elevation providers fail",
    freshnessWindow: "On demand with 6 hour elevation caching",
    nextActions: ["Adjust transect length", "Pair with terrain viewer", "Use slope context in analysis"],
    icon: "LineChart",
    category: "terrain",
    zone: "workspace",
    emphasis: "optional",
    defaultSize: "wide",
    defaultVisibility: false,
    defaultOrder: 80,
    requiredData: [],
    supportedProfiles: ["data-center", "hiking", "residential", "commercial"],
    emptyState: "Open this to inspect an elevation transect across the active region.",
  },
  {
    id: "image-upload",
    title: "Imagery tools",
    summary: "Upload imagery and add remote-sensing context.",
    questionAnswered: "What does a quick client-side pixel histogram suggest about this uploaded image?",
    regionCoverage: "Global - client-side only",
    failureMode: "Shows upload UI only until an image is selected or parsed successfully",
    freshnessWindow: "Immediate on upload",
    nextActions: ["Upload an image", "Open land classification", "Use results as a heuristic only"],
    icon: "ImagePlus",
    category: "media",
    zone: "workspace",
    emphasis: "optional",
    defaultSize: "standard",
    defaultVisibility: false,
    defaultOrder: 90,
    requiredData: [],
    supportedProfiles: ["data-center", "hiking", "residential", "commercial"],
    emptyState: "Upload imagery when you want image-based land-cover context.",
  },
  {
    id: "land-classifier",
    title: "Land classification",
    summary: "Review inferred land-cover buckets.",
    questionAnswered: "What rough land-cover mix does GeoSight infer from uploaded imagery or map context?",
    regionCoverage: "Global - heuristic client-side or geodata-derived estimates only",
    failureMode: "Shows only available buckets and hides zero-value classes",
    freshnessWindow: "Updates on upload or geodata-derived land-cover refresh",
    nextActions: ["Treat as heuristic", "Compare with map-derived land cover", "Open source awareness for limitations"],
    icon: "Leaf",
    category: "media",
    zone: "workspace",
    emphasis: "optional",
    defaultSize: "standard",
    defaultVisibility: false,
    defaultOrder: 100,
    requiredData: ["classification"],
    supportedProfiles: ["data-center", "hiking", "residential", "commercial"],
    emptyState: "Open land classification after uploading imagery or using geodata-derived cover.",
  },
  {
    id: "source-awareness",
    title: "Source awareness",
    summary: "Check provider freshness, coverage, and confidence.",
    questionAnswered: "Where did this location intelligence come from and how much should I trust it?",
    regionCoverage: "Global - reflects the active source registry context",
    failureMode: "Shows limited and unavailable states explicitly instead of hiding them",
    freshnessWindow: "Updates on geodata change",
    nextActions: ["Inspect a weak source", "Compare source limits across regions", "Use it to explain confidence in demos"],
    icon: "ShieldCheck",
    category: "context",
    zone: "workspace",
    emphasis: "secondary",
    defaultSize: "wide",
    defaultVisibility: false,
    defaultOrder: 110,
    requiredData: ["source-metadata"],
    supportedProfiles: ["data-center", "hiking", "residential", "commercial"],
    emptyState: "Review source freshness, coverage, and confidence here.",
  },
  {
    id: "school-context",
    title: "School context",
    summary: "Inspect nearby school context and official metrics.",
    questionAnswered: "What school signals are available here, and which parts are official versus GeoSight-derived?",
    regionCoverage: "US public K-12 baseline; strongest in Washington with official accountability data",
    failureMode: "Explains outside-US and no-match cases explicitly",
    freshnessWindow: "On demand with 24 hour source caching",
    nextActions: ["Check official Washington matches", "Use school context in residential due diligence", "Open sources for coverage limits"],
    icon: "GraduationCap",
    category: "planning",
    zone: "workspace",
    emphasis: "optional",
    defaultSize: "wide",
    defaultVisibility: false,
    defaultOrder: 115,
    requiredData: ["school-context"],
    supportedProfiles: ["data-center", "hiking", "residential", "commercial"],
    emptyState: "Open this to inspect nearby public-school context and Washington official metrics.",
  },
  {
    id: "hazard-context",
    title: "Hazard context",
    summary: "Earthquakes, active fires, and weather risk signals for the active area.",
    questionAnswered: "What live risk signals stand out at this location right now?",
    regionCoverage: "Global earthquakes via USGS; global fire via NASA FIRMS; global weather via Open-Meteo",
    failureMode: "Each signal degrades independently and shows status badge when limited or unavailable",
    freshnessWindow: "Earthquakes 6h / Fire 3h / Weather 6h",
    nextActions: ["Compare hazard signals across saved sites", "Open source awareness for data limits", "Ask GeoSight to interpret the risk profile"],
    icon: "ShieldAlert",
    category: "planning",
    zone: "workspace",
    emphasis: "secondary",
    defaultSize: "wide",
    defaultVisibility: false,
    defaultOrder: 116,
    requiredData: ["geodata"],
    supportedProfiles: ["data-center", "hiking", "residential", "commercial"],
    emptyState: "Select a location to see earthquake, fire, and weather hazard context.",
  },
  {
    id: "climate-history",
    title: "Climate trends (10-year)",
    summary: "Historical temperature and precipitation trends from 2015-2024.",
    questionAnswered: "Is this location warming, cooling, or stable over the past decade?",
    regionCoverage: "Global - Open-Meteo historical archive",
    failureMode: "Shows unavailable message if historical data cannot be retrieved",
    freshnessWindow: "Archived through previous calendar year",
    nextActions: ["Compare with current climate snapshot", "Review air quality trends"],
    icon: "TrendingUp",
    category: "analysis",
    zone: "workspace",
    emphasis: "secondary",
    defaultSize: "wide",
    defaultVisibility: true,
    defaultOrder: 85,
    requiredData: ["geodata"],
    supportedProfiles: ["data-center", "hiking", "residential", "commercial"],
    emptyState: "Select a location to see 10-year climate trends.",
  },
  {
    id: "broadband-context",
    title: "Broadband context",
    summary: "Peak speeds, provider count, and technology mix for the active point.",
    questionAnswered: "How strong is the fixed-broadband baseline here right now?",
    regionCoverage: "United States only via FCC Broadband Map",
    failureMode: "Shows unavailable or limited state explicitly when the FCC endpoint or region is unsupported",
    freshnessWindow: "Cached up to 24 hours",
    nextActions: ["Compare another corridor", "Pair with mission score", "Open source awareness for limits"],
    icon: "Wifi",
    category: "planning",
    zone: "workspace",
    emphasis: "secondary",
    defaultSize: "standard",
    defaultVisibility: false,
    defaultOrder: 118,
    requiredData: ["geodata", "score"],
    supportedProfiles: ["data-center", "residential"],
    emptyState: "Select a US location to inspect FCC broadband availability context.",
  },
  {
    id: "flood-risk",
    title: "Flood risk",
    summary: "Read the FEMA flood-zone designation with a simple risk badge.",
    questionAnswered: "Is this point inside a mapped Special Flood Hazard Area or a lower-risk zone?",
    regionCoverage: "United States only via FEMA NFHL",
    failureMode: "Shows unsupported region or missing FEMA response instead of inferring flood safety",
    freshnessWindow: "Cached up to 24 hours",
    nextActions: ["Compare another parcel", "Cross-check local floodplain rules", "Use with residential due diligence"],
    icon: "Waves",
    category: "planning",
    zone: "workspace",
    emphasis: "secondary",
    defaultSize: "standard",
    defaultVisibility: false,
    defaultOrder: 119,
    requiredData: ["geodata"],
    supportedProfiles: ["data-center", "residential"],
    emptyState: "Select a US location to inspect FEMA flood-zone context.",
  },
  {
    id: "cooling-water",
    title: "Cooling water",
    summary: "Nearest stream gauge, discharge, and mapped water access for cooling context.",
    questionAnswered: "Is there a meaningful nearby water source with live USGS discharge context?",
    regionCoverage: "United States gauges plus mapped waterways elsewhere",
    failureMode: "Falls back to mapped water proximity when no live USGS gauge is nearby",
    freshnessWindow: "Waterways on location change; gauges cached 15-30 minutes",
    nextActions: ["Compare gauge volumes across sites", "Cross-check permitting and rights", "Pair with flood risk"],
    icon: "Droplets",
    category: "planning",
    zone: "workspace",
    emphasis: "secondary",
    defaultSize: "wide",
    defaultVisibility: false,
    defaultOrder: 120,
    requiredData: ["geodata"],
    supportedProfiles: ["data-center"],
    emptyState: "Select a location to inspect nearby mapped water and USGS gauge context.",
  },
  {
    id: "groundwater",
    title: "Groundwater levels",
    summary: "Nearby USGS monitoring wells and current water table depth.",
    questionAnswered: "How deep is the water table here and what does it mean for construction or water access?",
    regionCoverage: "United States - USGS groundwater monitoring network",
    failureMode: "Shows unavailable message when no wells are in range",
    freshnessWindow: "Live readings within 30 days",
    nextActions: ["Check soil profile for drainage context", "Compare with flood risk"],
    icon: "Droplets",
    category: "analysis",
    zone: "workspace",
    emphasis: "secondary",
    defaultSize: "standard",
    defaultVisibility: false,
    defaultOrder: 180,
    requiredData: ["geodata"],
    supportedProfiles: ["data-center", "residential", "hiking", "commercial"],
    emptyState: "Select a US location to see groundwater monitoring data.",
  },
  {
    id: "soil-profile",
    title: "Soil profile",
    summary: "USDA soil type, drainage, depth to bedrock, and water table.",
    questionAnswered: "What kind of ground is beneath this location and what does it mean for building or drainage?",
    regionCoverage: "United States - NRCS SSURGO soil survey",
    failureMode: "Shows unavailable message when soil data is not mapped",
    freshnessWindow: "Periodic survey updates",
    nextActions: ["Check groundwater levels", "Review flood risk", "Assess terrain"],
    icon: "Layers",
    category: "analysis",
    zone: "workspace",
    emphasis: "secondary",
    defaultSize: "standard",
    defaultVisibility: false,
    defaultOrder: 190,
    requiredData: ["geodata"],
    supportedProfiles: ["data-center", "residential", "hiking", "commercial"],
    emptyState: "Select a US location to see soil survey data.",
  },
  {
    id: "seismic-design",
    title: "Seismic risk profile",
    summary: "USGS site-specific seismic hazard and design parameters.",
    questionAnswered: "What is the statistical ground shaking risk at this site for the next 50 years?",
    regionCoverage: "United States - USGS seismic design maps (ASCE 7-22)",
    failureMode: "Shows unavailable message outside US coverage",
    freshnessWindow: "Based on ASCE 7-22 reference document",
    nextActions: ["Check earthquake history", "Review terrain stability"],
    icon: "Activity",
    category: "analysis",
    zone: "workspace",
    emphasis: "secondary",
    defaultSize: "standard",
    defaultVisibility: false,
    defaultOrder: 200,
    requiredData: ["geodata"],
    supportedProfiles: ["data-center", "residential", "commercial"],
    emptyState: "Select a US location to see seismic design parameters.",
  },
  {
    id: "air-quality",
    title: "Air quality",
    summary: "Nearest particle-monitoring station context with a color-coded AQI badge.",
    questionAnswered: "What does the nearest live PM2.5 / PM10 reading suggest about air quality here?",
    regionCoverage: "Global where OpenAQ stations exist; Open-Meteo fallback context where they do not",
    failureMode: "Shows station gaps explicitly instead of guessing air quality",
    freshnessWindow: "Cached up to 30 minutes",
    nextActions: ["Compare nearby neighborhoods or trailheads", "Use with climate context", "Inspect source status"],
    icon: "Wind",
    category: "planning",
    zone: "workspace",
    emphasis: "secondary",
    defaultSize: "standard",
    defaultVisibility: false,
    defaultOrder: 121,
    requiredData: ["geodata"],
    supportedProfiles: ["hiking", "residential"],
    emptyState: "Select a location to inspect OpenAQ or Open-Meteo air-quality context.",
  },
  {
    id: "contamination-risk",
    title: "Contamination screening",
    summary: "Nearby Superfund and TRI context with a warning badge for close-in sites.",
    questionAnswered: "Are there contamination-screening signals nearby that deserve due diligence?",
    regionCoverage: "United States only via EPA Envirofacts",
    failureMode: "Shows unsupported region or unavailable EPA screening explicitly",
    freshnessWindow: "Cached up to 12 hours",
    nextActions: ["Cross-check parcel and remediation history", "Compare another candidate", "Use with flood and school context"],
    icon: "TriangleAlert",
    category: "planning",
    zone: "workspace",
    emphasis: "optional",
    defaultSize: "standard",
    defaultVisibility: false,
    defaultOrder: 122,
    requiredData: ["geodata"],
    supportedProfiles: ["data-center", "residential"],
    emptyState: "Select a US location to inspect nearby EPA contamination-screening context.",
  },
] as const;

export const WORKSPACE_CARD_GROUPS = [
  { key: "context", label: "Core context" },
  { key: "analysis", label: "Analysis" },
  { key: "planning", label: "Planning" },
  { key: "terrain", label: "Terrain tools" },
  { key: "media", label: "Imagery tools" },
  { key: "comparison", label: "Comparison" },
] as const;

export const WORKSPACE_CARD_MAP = Object.fromEntries(
  WORKSPACE_CARD_REGISTRY.map((card) => [card.id, card]),
) as Record<WorkspaceCardId, WorkspaceCardDefinition>;

const PROFILE_VISIBLE_CARD_DEFAULTS: Record<string, WorkspaceCardId[]> = {
  "data-center": ["active-location", "chat", "results", "score", "cooling-water", "broadband-context", "factor-breakdown", "mission-run"],
  hiking: ["active-location", "chat", "results", "score", "terrain-viewer", "air-quality"],
  residential: ["active-location", "chat", "results", "score", "school-context", "flood-risk", "air-quality", "contamination-risk", "source-awareness", "mission-run"],
  commercial: ["active-location", "chat", "results", "score", "mission-run"],
};

export function getWorkspaceCardDefaults(profileId: string) {
  const visibleSet = new Set(
    PROFILE_VISIBLE_CARD_DEFAULTS[profileId] ?? PROFILE_VISIBLE_CARD_DEFAULTS.commercial,
  );

  return WORKSPACE_CARD_REGISTRY.reduce<Record<WorkspaceCardId, boolean>>((acc, card) => {
    acc[card.id] =
      visibleSet.has(card.id) ||
      (card.defaultVisibility && !visibleSet.has(card.id) ? card.defaultVisibility : visibleSet.has(card.id));
    return acc;
  }, {} as Record<WorkspaceCardId, boolean>);
}

export function getWorkspaceCardsForProfile(profileId: string) {
  return WORKSPACE_CARD_REGISTRY.filter((card) => card.supportedProfiles.includes(profileId)).sort(
    (a, b) => a.defaultOrder - b.defaultOrder,
  );
}

export function mergeWorkspacePreferences(
  profileId: string,
  preferences: Partial<Record<WorkspaceCardId, boolean>> = {},
) {
  const defaults = getWorkspaceCardDefaults(profileId);

  return Object.keys(defaults).reduce<Record<WorkspaceCardId, boolean>>((acc, key) => {
    const cardId = key as WorkspaceCardId;
    acc[cardId] = preferences[cardId] ?? defaults[cardId];
    return acc;
  }, {} as Record<WorkspaceCardId, boolean>);
}

export function toWorkspaceCardPreferences(
  visibility: Record<WorkspaceCardId, boolean>,
) {
  return Object.entries(visibility).map(([cardId, visible]) => ({
    cardId: cardId as WorkspaceCardId,
    visible,
  })) satisfies WorkspaceCardPreference[];
}
