import type { SavedSite } from "@/types";

export const DEMO_SAVED_SITES: SavedSite[] = [
  {
    id: "demo-bellevue-wa",
    name: "Bellevue, WA",
    regionName: "King County, WA",
    profileId: "home-buying",
    coordinates: { lat: 47.6101, lng: -122.2015 },
    score: {
      total: 81,
      recommendation: "Strong candidate — highly livable metro with excellent schools, low seismic-day risk, and strong broadband coverage.",
      broadband: null,
      factors: [
        {
          key: "school_quality",
          label: "School quality",
          score: 88,
          weight: 0.2,
          detail: "Bellevue School District ranks among the top districts in Washington State.",
          evidenceKind: "derived_live",
          evidenceLabel: "Derived live",
          evidenceExplanation: "Derived from NCES enrollment and state accountability data.",
        },
        {
          key: "climate_comfort",
          label: "Climate comfort",
          score: 79,
          weight: 0.15,
          detail: "Mild maritime climate with cool wet winters and warm dry summers.",
          evidenceKind: "derived_live",
          evidenceLabel: "Derived live",
          evidenceExplanation: "Derived from Open-Meteo climate normals.",
        },
        {
          key: "hazard_exposure",
          label: "Hazard exposure",
          score: 72,
          weight: 0.2,
          detail: "Low wildfire risk; moderate seismic zone due to proximity to Cascadia Subduction Zone.",
          evidenceKind: "derived_live",
          evidenceLabel: "Derived live",
          evidenceExplanation: "Derived from USGS seismic design values and NASA FIRMS fire data.",
        },
      ],
    },
    note: "Demo site — replace with a real saved location.",
  },
  {
    id: "demo-austin-tx",
    name: "Austin, TX",
    regionName: "Travis County, TX",
    profileId: "home-buying",
    coordinates: { lat: 30.2672, lng: -97.7431 },
    score: {
      total: 74,
      recommendation: "Good candidate — strong job market and amenities, but heat stress and flooding risk warrant further due diligence.",
      broadband: null,
      factors: [
        {
          key: "school_quality",
          label: "School quality",
          score: 71,
          weight: 0.2,
          detail: "Austin ISD has broad coverage with several top-rated magnet and charter schools.",
          evidenceKind: "derived_live",
          evidenceLabel: "Derived live",
          evidenceExplanation: "Derived from NCES enrollment and state accountability data.",
        },
        {
          key: "climate_comfort",
          label: "Climate comfort",
          score: 62,
          weight: 0.15,
          detail: "Hot semi-arid climate with long summers; heat stress risk increasing with climate trajectory.",
          evidenceKind: "derived_live",
          evidenceLabel: "Derived live",
          evidenceExplanation: "Derived from Open-Meteo climate normals and CDD projections.",
        },
        {
          key: "hazard_exposure",
          label: "Hazard exposure",
          score: 68,
          weight: 0.2,
          detail: "Low seismic risk; localized flash flood risk in eastern Austin watersheds.",
          evidenceKind: "derived_live",
          evidenceLabel: "Derived live",
          evidenceExplanation: "Derived from FEMA flood zone data and USGS seismic design values.",
        },
      ],
    },
    note: "Demo site — replace with a real saved location.",
  },
];
